# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Dirty models: the math of how soil breaths'
description: > # this means to ignore newlines until "baseurl:"
  Field notes of a computational terrestrial biogeochemist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ktoddbrown.github.io" # the base hostname & protocol for your site
twitter_username: KatheMathBio
github_username:  ktoddbrown

# This is the list of pages to incldue in the header of the website.
pages_list:       {'Abount':'/about','Archive':'/archive'}
# Build settings
markdown: kramdown
